import { useEffect, useState } from 'react'
import { api } from '../api/client'
import type { Device, Subject } from '../api/types'

export default function DevicesPage() {
  const [devices, setDevices] = useState<Device[]>([]); const [subjects, setSubjects] = useState<Subject[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState('')
  async function load() { setLoading(true); setError(''); try { const [nextDevices, nextSubjects] = await Promise.all([api.listDevices(), api.listSubjects()]); setDevices(nextDevices); setSubjects(nextSubjects) } catch (e) { setError(e instanceof Error ? e.message : '请求失败') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const filtered = devices.filter(item => `${item.name} ${item.id} ${item.subject_id}`.toLowerCase().includes(query.toLowerCase()))
  return <section><div className="page-title"><div><p className="eyebrow">资源管理</p><h2>设备与主体</h2><p className="muted">查看主体关联设备与最近在线状态</p></div><button className="secondary" onClick={load}>刷新数据</button></div>{error && <div className="state error-state"><strong>加载失败</strong><span>{error}</span><button className="secondary" onClick={load}>重试</button></div>}{loading ? <div className="state">正在加载设备数据...</div> : <><div className="resource-summary"><div><strong>{subjects.length}</strong><span>主体</span></div><div><strong>{devices.length}</strong><span>设备</span></div><div><strong>{devices.filter(d => d.status !== 'offline').length}</strong><span>在线或未知</span></div></div><div className="toolbar"><label className="search-field">搜索设备<input aria-label="搜索设备" placeholder="名称、设备 ID 或主体 ID" value={query} onChange={e => setQuery(e.target.value)} /></label></div>{filtered.length ? <div className="table-wrap"><table><thead><tr><th>设备</th><th>主体</th><th>状态</th><th>最近心跳</th></tr></thead><tbody>{filtered.map(device => <tr key={device.id}><td><strong>{device.name}</strong><small>{device.id}</small></td><td>{subjects.find(s => s.id === device.subject_id)?.name || device.subject_id}</td><td><span className={`status status-${device.status === 'offline' ? 'down' : 'healthy'}`}>{device.status || '正常'}</span></td><td>{device.last_seen_at ? new Date(device.last_seen_at).toLocaleString('zh-CN') : '暂无记录'}</td></tr>)}</tbody></table></div> : <div className="state empty">{query ? '没有匹配的设备' : '暂无设备'}</div>}</>}</section>
}
