import { useEffect, useState } from 'react'
import { api } from '../api/client'
import type { Event, EventDetail, WorkRole } from '../api/types'

export default function EventsPage() {
  const [role, setRole] = useState<WorkRole | ''>(''); const [query, setQuery] = useState(''); const [events, setEvents] = useState<Event[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [detail, setDetail] = useState<EventDetail | null>(null); const [detailLoading, setDetailLoading] = useState(false)
  async function load() { setLoading(true); setError(''); try { setEvents(await api.listEvents(role || undefined)) } catch (e) { setError(e instanceof Error ? e.message : '加载失败') } finally { setLoading(false) } }
  useEffect(() => { load() }, [role])
  const visible = events.filter(event => `${event.event_type} ${event.event_id} ${event.subject_id} ${event.device_id}`.toLowerCase().includes(query.toLowerCase()))
  async function openDetail(id: string) { setDetailLoading(true); setDetail(null); try { setDetail(await api.getEvent(id)) } catch (e) { setMessage(e instanceof Error ? e.message : '详情加载失败') } finally { setDetailLoading(false) } }
  async function tombstone(id: string) { try { await api.tombstoneEvent(id, '管理员处理'); setEvents(old => old.filter(e => e.event_id !== id)); setMessage('事件已归档') } catch (e) { setMessage(e instanceof Error ? e.message : '归档失败') } }
  return <section><div className="page-title"><div><p className="eyebrow">运行记录</p><h2>事件</h2><p className="muted">按角色与关键词定位运行事件</p></div><button className="secondary" onClick={load}>刷新数据</button></div><div className="toolbar event-toolbar"><label>工作角色<select aria-label="工作角色筛选" value={role} onChange={e => setRole(e.target.value as WorkRole | '')}><option value="">全部角色</option><option>研发</option><option>测试</option><option>产品</option></select></label><label className="search-field">搜索<input aria-label="搜索事件" placeholder="事件类型、主体或设备" value={query} onChange={e => setQuery(e.target.value)} /></label></div>{message && <p className="notice">{message}</p>}{error && <div className="state error-state"><strong>加载失败</strong><span>{error}</span><button className="secondary" onClick={load}>重试</button></div>}{loading ? <div className="state">正在加载事件...</div> : visible.length === 0 ? <div className="state empty">{query ? '没有匹配的事件' : '暂无事件'}</div> : <div className="table-wrap"><table><thead><tr><th>事件</th><th>主体 / 设备</th><th>角色</th><th>发生时间</th><th>操作</th></tr></thead><tbody>{visible.map(event => <tr key={event.event_id}><td><strong>{event.event_type}</strong><small>{event.event_id}</small></td><td>{event.subject_id}<small>{event.device_id}</small></td><td>{event.work_role || '-'}</td><td>{new Date(event.occurred_at).toLocaleString('zh-CN')}</td><td className="actions"><button className="secondary" onClick={() => openDetail(event.event_id)}>查看详情</button><button className="text-button" onClick={() => tombstone(event.event_id)}>归档</button></td></tr>)}</tbody></table></div>}{(detailLoading || detail) && <div className="drawer-backdrop" role="presentation" onClick={() => setDetail(null)}><aside className="drawer" onClick={e => e.stopPropagation()}><div className="panel-heading"><div><p className="eyebrow">事件详情</p><h3>{detail?.event_type || '加载中...'}</h3></div><button className="icon-button" aria-label="关闭详情" onClick={() => setDetail(null)}>×</button></div>{detailLoading ? <div className="state">正在加载详情...</div> : detail && <div className="detail-list"><div><span>事件 ID</span><strong>{detail.event_id}</strong></div><div><span>主体</span><strong>{detail.subject_id}</strong></div><div><span>设备</span><strong>{detail.device_id}</strong></div><div><span>摘要</span><strong>{detail.summary || '无摘要'}</strong></div>{detail.payload && <div><span>payload</span><pre>{JSON.stringify(detail.payload, null, 2)}</pre></div>}</div>}</aside></div>}</section>
}
